InfluxDB:
  image: influxdb:1.4.3-alpine
  ports:
    - 8086:8086
    - 8083:8083
    - 8099:8099
    - 8090:8090
  volumes:
    - /var/influxdb:/var/lib/influxdb
  environment:
    - INFLUXDB_DB=collection
    - INFLUXDB_USER=influxuser
    - INFLUXDB_USER_PASSWORD=influxuserpwd

Grafana:
  image: grafana/grafana
  ports:
    - 3000:3000
  volumes:
    - /var/grafana/lib:/var/lib/grafana
  links:
    - InfluxDB
