InfluxDB:
  image: influxdb:1.5-alpine
  ports:
    - 8086:8086
    - 8083:8083
    - 8099:8099
    - 8090:8090
  volumes:
    - ~/influxdb:/var/lib/influxdb
  environment:
    - INFLUXDB_DB=statistics
    - INFLUXDB_WRITE_USER=influxuser
    - INFLUXDB_WRITE_USER_PASSWORD=influxuserpwd
    - INFLUXDB_ADMIN_ENABLED=true
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=admin

Grafana:
  image: grafana/grafana
  ports:
    - 3000:3000
  volumes:
    - ~/grafana/lib:/var/lib/grafana
  links:
    - InfluxDB
